### ISSUE TITLE
Configuration of ssh-simple using Mock SSH Responses

### ISSUE THREAD

**Issue by benpingilley** [mdsummers/mock-ssh-responses#1]
Configuring simple-ssh with mock-ssh-responses is easy AND took an entire day to figure out. Will you update the documentation to show this configuration method so other do not also waste time?

On the command line, using the ssh examples you have documented is the same as forcing the ssh command to use the generated key and setting the host to localhost.
- ```ssh <username>@mock-answers.yml id nobody```
SAME AS
- ```ssh -i <path_to_key>/.ssh/mocked-localhost <username>@localhost id nobody``` 

So when configuring the simple-ssh module, use the generated key and ```localhost``` rather than ```mock-answers.yml``` like the documentation led me to believe.

```
function getSSH (req, res) {
  const SSH = require('simple-ssh');
  const fs = require('fs');
  const key = fs.readFileSync('<path_to_key>/.ssh/mocked-localhost');
  const ssh = new SSH({
    host: 'localhost',
    user: '<username>',
    key: key
  });

  ssh.exec('id nobody', {
    exit: function(code, stdout, stderr) {
      res.send(code, stdout, stderr);
    }
  }).start();
}

module.exports = { getSSH };
```

**Comment by mdsummers** [comment]
Hi there. `simple-ssh` is using the `ssh2` client in the background, which is not going to consult your `~/.ssh/config` file.

That's not a problem, as all this is doing is seeing you're trying to ssh to `mock-answers.yml` and replace the hostname with localhost and the key with the correct one for the connection.

In your example above try changing
```
  host: 'mock-answers.yml',
```
to
```
  host: 'localhost',
```
and give it another go. I'm finding that to work with your example

**Comment by benpingilley** [comment]
Thanks for the update. I thought I had updated my comment with how to do it. Figured it out a few minutes after posting.
